services:
  exif-db:
    image: dbryanjohnson/exif-db:latest
    ports:
      - "8668:8000" 
    volumes:
      - /volume1/photo:/photo
      - /volume1/docker/appdata/exif-db:/storage
    environment:
      - TZ=America/Detroit
      - MAX_IMAGE_SIZE=2000
      - DEFAULT_NUM_IMAGES=20
    working_dir: /src/app
    command: uvicorn api:app --workers 2 --host 0.0.0.0 --port 8000

