services:
  exif-db:
    build: .
    ports:
      - "8668:8000" 
    volumes:
      - ./photo:/photo
      - ./storage:/storage
      - .:/src/app
    environment:
      - TZ=America/Detroit
      - MAX_IMAGE_SIZE=2000
    working_dir: /src/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
