services:
  exif-db:
    build: .
    ports:
      - "8668:8000" 
    volumes:
      - /volume1/photo:/photo
      - .:/storage
      - .:/src/app
    environment:
      - TZ=America/Detroit
    working_dir: /src/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
